#!/usr/bin/env python2.7
from __future__ import print_function

from antipathy import Path
from scription import *
from codecs import open
from re import match, search

@Command(
        term=('expression to search for', ),
        files=Spec('templates of file names to search', type=Path),
        re=('term is a regex', FLAG),
        all=('check all matching files', FLAG),
        encoding=Spec('encoding of file(s)', OPTION, force_default='latin1'),
        )
def check_logs(term, re, all, encoding, *files):
    if not files:
        help('no FILES specified')
    for template in files:
        original = template.glob()
        matches = set((template+'*').glob())
        matches = matches - set(original)
        matches = original + sorted(list(matches), reverse=True)
        if matches:
            if not all:
                matches = [matches[:2][-1]]
        else:
            abort('unable to find any matches for %r' % template)
        for fn in matches:
            print('checking', fn)
            with open(fn, encoding=encoding) as fh:
                in_error = seen = False
                for line in fh:
                    if in_error and not match('\d{4}-\d{2}-\d{2} ', line):
                        echo(line, end='')
                        continue
                    in_error = False
                    if re:
                        if search(term, line):
                            in_error = True
                            if not seen:
                                seen = True
                                echo()
                                echo(fn, border='box')
                            echo(line, end='')
                    elif term in line:
                        in_error = True
                        if not seen:
                            seen = True
                            echo(fn, border='box')
                        echo(line, end='')

Main()
