#!/usr/bin/env python2.7

from itertools import groupby
from textwrap import dedent
from scription import *, Execute, mail

try:
    execfile('/etc/evs/cronaide.conf')
except:
    message = dedent("""\
            To: %s
            From: cron_check <noreply@nowhere.invalid>
            Subject: %s

            %s""")
    mail_server = 'localhost'

@Command(
        user=('Who to send a test mail to.',),
        server=('Server to use', OPTION),
        )
def test_mail(user, server=mail_server):
    msg = message % (user, 'test mail', 'hope you got this! :)')
    mail(mail_server, 25, msg)


@Command()
def check_cron():
    with open('/etc/crontab') as crontab:
        warnings = []
        for line in crontab:
            if line.startswith('#:cron_check:'):
                _, email, prog = line.rsplit(':', 2)
                cron_check = next(crontab)
                if cron_check[0] == '#':
                    addresses = email.split(',')
                    for addr in addresses:
                        warnings.append((addr, prog))
        warnings.sort()
        for email, progs in groupby(warnings, key=lambda ep: ep[0]):
            prog_names = []
            for _, prog in progs:
                prog_names.append(prog)
            msg = message % (email, 'disabled cron jobs', '\t%s'%'\n\t'.join(prog_names))
            mail(mail_server, 25, msg)
