#!/usr/bin/python
from __future__ import print_function
import os
from datetime import datetime
from antipathy import Path
from scription import *

@Command(
        name=('file name(s) or directory name(s) to search for', ),
        path=('starting path (defaults to cwd)', OPTION, 'p', Path),
        files_only=('only search file names', FLAG),
        dirs_only=('only search dir names', FLAG),
        timestamp=('display timestamp of file', FLAG,),
        )
def filesearch(files_only, dirs_only, timestamp, path='./', *name):
    "Searches for `name` in `path`."
    for tree, dirs, files in path.walk():
        if not files_only:
            for d in dirs:
                for n in name:
                    if n in d:
                        print(tree/d, verbose=0)
        if not dirs_only:
            for f in files:
                for n in name:
                    if n in f:
                        if timestamp:
                            print(datetime.fromtimestamp((tree/f).stat()[8]), '   ', tree/f, verbose=0)       # mtime
                        else:
                            print(tree/f, verbose=0)       # mtime

Run()
