#!/usr/local/bin/python

from __future__ import print_function

from scription import *
from VSS.BBxXlate.fisData import fisData

@Command(
        table=Spec('FIS table to query', type=int),
        code=Spec('code to search for', ),
        field=Spec('specific fields to display [default: all, counting starts with 1]', MULTI, type=int),
        )
def fis_query(table, code, field):
    key = table_keys.get(table)
    fis_table = fisData(table, keymatch=key)
    if not field:
        print(fis_table[code], verbose=0)
    else:
        field = [x-1 for x in field]
        lines = []
        record = fis_table[code]
        name = value = 0
        for i, row in enumerate(record.fieldlist):
            if i in field:
                name = max(len(row[3]), name)
                value = max(len(str(record[row[3]])), value)
        for i, row in enumerate(record.fieldlist):
            if i in field:
                if '$' in row[3]:
                    lines.append('%5d | %*s | %*s | %s' % (i+1, -name, row[3], -value, record[row[3]], row[1]))
                else:
                    lines.append('%5d | %*s | %*s | %s' % (i+1, -name, row[3], value, record[row[3]], row[1]))
        print('\n'.join(lines), verbose=0)
        


table_keys = {
    328: '10%s000010000',
    }


Run()

