#!/usr/local/sbin/suid-python
from __future__ import print_function

from antipathy import Path
from scription import *

import grp
import pwd

@Command(
        repo=Spec('root directory of repo', type=Path),
        )
def set_owner_of(repo):
    "sets the root directory owner as owner of all sub-files/directories"
    print('setting owner of:', repo)
    stat = repo.stat()
    uid = stat.st_uid
    gid = stat.st_gid
    print('to:', uid, gid)
    user = pwd.getpwuid(uid).pw_name
    group = grp.getgrgid(gid).gr_name
    print('   ', user, group)
    job = Execute('chown -R %s:%s %s' % (user, group, repo))
    echo(job.stdout, end='')
    error(job.stderr, end='')
    print('return code:', job.returncode)
    raise SystemExit(job.returncode)

@Command(
        repo=Spec('root directory of repo', type=Path),
        )
def add_group_write_to(repo):
    "adds the group write permission bit"
    print('adding write bit to', repo)
    job = Execute('chmod -R g+w %s' % repo)
    echo(job.stdout, end='')
    error(job.stderr, end='')
    print('return code:', job.returncode)
    raise SystemExit(job.returncode)

Main()
