#!/usr/bin/python
"""
tree view of file system:

/
|-- vmlinuz
|-- vmlinuz.old
|
|-- home/
|   |-- alpha/
|   |  `-- Desktop/
|   |
|   `-- echo/
|      |-- Desktop/
|      `-- Downloads/
|
`-- var/
"""
from __future__ import print_function
from antipathy import Path
from scription import *
from time import time

@Command(
        path=Spec('path to examine', REQUIRED, None, default=Path.getcwd()),
        include_files=('show files', FLAG, 'f'),
        omit_dirs=('do not recurse into these directories', MULTI, 'o'),
        time_it=('time execution', FLAG, 't'),
        hidden=('show hidden files/directories', FLAG),
        links=('follow links', FLAG, 'l'),
        depth=Spec('limit recursion to x levels', OPTION, type=int, default=None),
        )
def tree(path, include_files, omit_dirs, hidden, links, depth, time_it=False, _prefix=''):
    if path.isfile() or not path.exists():
        abort('%s is not a valid path' % (path, ))
    if omit_dirs and isinstance(omit_dirs[0], unicode):
        omit_dirs = [d.encode('utf8') for d in omit_dirs]
    if time_it:
        start = time()
    if not _prefix:
        print(path/'', sep='', verbose=0)
    if depth is not None:
        depth -= 1
    for current, dirs, files in path.walk():
        if not include_files:
            files = []
        if omit_dirs:
            dirs[:] = [d for d in dirs if d not in omit_dirs]
        if not hidden:
            files[:] = [f for f in files if not f.startswith('.')]
            dirs[:] = [d for d in dirs if not d.startswith('.')]
        dirs.sort()
        files.sort()
        last_dir = last_file = None
        if files and not dirs:
            last_file = files.pop()
        if dirs:
            last_dir = dirs.pop()
        for file in files:
            link = ('', ' [l]')[(current/file).islink()]
            print(_prefix, '|-- ', file, link, sep='', verbose=0)
        if last_file:
            link = ('', ' [l]')[(current/last_file).islink()]
            print(_prefix, '`-- ', last_file, link, sep='', verbose=0)
        for dir in dirs:
            link = ('', ' [l]')[(current/dir).islink()]
            print(_prefix, '|-- ', dir, '/', link, sep='', verbose=0)
            if links or not (current/dir).islink():
                if depth is None or depth >= 0:
                    tree(current/dir, include_files, omit_dirs, hidden, links, depth=depth, _prefix=_prefix+'|  ')
        if last_dir:
            link = ('', '[l]')[(current/last_dir).islink()]
            print(_prefix, '`-- ', last_dir, '/', link, sep='', verbose=0)
            if links or not (current/last_dir).islink():
                if depth is None or depth >= 0:
                    tree(current/last_dir, include_files, omit_dirs, hidden, links, depth=depth, _prefix=_prefix+'   ')
        dirs[:] = []
    if time_it:
        end = time()
        print('\n', '%5.2f seconds have elapsed' % (end-start), sep='', verbose=0)
Run()
