#!/usr/bin/env python2.7
"""
tree view of file system:

/
|-- vmlinuz
|-- vmlinuz.old
|
|-- home/
|   |-- alpha/
|   |  `-- Desktop/
|   |
|   `-- echo/
|      |-- Desktop/
|      `-- Downloads/
|
`-- var/
"""
from __future__ import print_function
from antipathy import Path
from scription import *
from time import time

# API
@Command(
        path=Spec('path to examine', REQUIRED, None, default=Path.getcwd()),
        include_files=('show files', FLAG, 'f'),
        omit_dirs=('do not recurse into these directories', MULTI, 'o'),
        time_it=('time execution', FLAG, 't'),
        hidden=('show hidden files/directories', FLAG),
        links=('follow links', FLAG, 'l'),
        depth=Spec('limit recursion to x levels', OPTION, type=int, default=None),
        usage=('show disk usage', FLAG),
        min_size=Spec('minimum size to show', OPTION, type=int),
        )
def tree(path, include_files, omit_dirs, hidden, links, depth, usage, min_size, time_it=False, _prefix=''):
    if path.isfile() or not path.exists():
        abort('%s is not a valid path' % (path, ))
    if omit_dirs and isinstance(omit_dirs[0], unicode):
        omit_dirs = [d.encode('utf8') for d in omit_dirs]
    if time_it:
        start = time()
    if not _prefix:
        echo(path/'', '[%s]' % size_of_dir(path))
    if depth is not None:
        depth -= 1
    for current, dirs, files in path.walk():
        if not include_files:
            files = []
        if omit_dirs:
            dirs[:] = [d for d in dirs if d not in omit_dirs]
        if not hidden:
            files[:] = [f for f in files if not f.startswith('.')]
            dirs[:] = [d for d in dirs if not d.startswith('.')]
        #
        dirs.sort()
        print_dirs = []
        for dir in dirs:
            link = ('', ' [l]')[(current/dir).islink()]
            size_text = ''
            if usage and not link:
                size = size_of_dir(current/dir)
                if size >= min_size:
                    size_text = '--| %7s |--' % humanize(size)
            dir = '|-- %s %s' % (dir, link)
            print_dirs.append((dir, size_text, '|  '))
        if print_dirs:
            pdir, size_text, add_prefix = print_dirs[-1]
            pdir = pdir.replace('|-- ', '`-- ')
            print_dirs[-1] = (pdir, size_text, '   ')
        #
        files.sort()
        new_files = []
        for file in files:
            link = ('', ' [l]')[(current/file).islink()]
            size_text = ''
            if usage and not link:
                size = size_of_file(current/file)
                if size >= min_size:
                    size_text = '--| %7s |--' % humanize(size)
            file = '|-- %s %s' % (file, link)
            new_files.append((file, size_text))
        files = new_files
        if files and not dirs:
            file, size_text = files[-1]
            file = file.replace('|-- ', '`-- ')
            files[-1] = (file, size_text)
        #
        for file, size_text in files:
            leader = '%s%s' % (_prefix, file)
            echo('%-70s%s' % (leader, size_text))
        for dir, (pdir, size_text, add_prefix) in zip(dirs, print_dirs):
            leader = '%s%s' % (_prefix, pdir)
            echo('%-70s%s' % (leader, size_text))
            if links or not (current/dir).islink():
                if depth is None or depth >= 0:
                    tree(
                            current/dir,
                            include_files,
                            omit_dirs,
                            hidden,
                            links,
                            depth=depth,
                            usage=usage,
                            min_size=min_size,
                            _prefix=_prefix+add_prefix,
                            )
        dirs[:] = []
    if time_it:
        end = time()
        echo('\n', '%5.2f seconds have elapsed' % (end-start), sep='')

# helpers

def size_of_dir(dir):
    "return human readable sizes directories"
    total = sum([(dir/e).stat().st_size for e in dir.listdir() if not (dir/e).islink() and not (dir/e).isdir()])
    return total

def size_of_file(file):
    "return human readable sizes of files"
    total = file.stat().st_size
    return total

def humanize(size):
    "convert to human readable size"
    for prefix in (' b', 'kb', 'mb', 'gb', 'tb', 'pb', 'eb', 'zb', 'yb'):
        if size > 1024:
            size /= 1024
        else:
            break
    string = '%s %s' % (size, prefix)
    return string

Run()
